# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
    volumes:
      - '/srv/docker/itop/db:/var/lib/mysql'
  itop:
    build: .
    restart: always
    ports:
      - 8080:80
    links:
      - db
    depends_on:
      - db
